apiVersion: v1
kind: Service
metadata:
  name: ticker-cal-tracker
  labels:
    app: ticker-cal-tracker
spec:
  type: LoadBalancer
  selector:
    app: ticker-cal-tracker
  ports:
    - name: http
      port: 80
      targetPort: 5001
